### ISSUE TITLE
If we value something, what is the next step? 

### ISSUE THREAD

**Issue by joshdance** [scottefein/the-happiness-manifesto#2]
Great start to the manifesto. Just wondering about the next step after valuing something. If we value something, do we promote it? Seek for more of it? What is the next action step for valuing something?

**Comment by scottefein** [comment]
We share it. We talk about it. We decide these are the things we're interested in as a community and then we open up the tent to everyone who buys in. Individuals get their teams bought into it, it's a question you can ask when you're building a new project or adopting a new technology. We hack on projects with these ideals, we give presentations and discuss the technologies involved.

**Comment by joshdance** [comment]
Share. Discuss. Hack. Present. I like it!
