### ISSUE TITLE
Clarity and comphrehension

### ISSUE THREAD

**Issue by nathany** [scottefein/the-happiness-manifesto#8]
Maintainable code sort of covers it, but could be expanded.

Clarity over cleverness. 

We read code much more than we write code.

**Comment by scottefein** [comment]
I like that, something along the lines of "We value maintainable code, emphasizing clarity over cleverness"?

**Comment by nathany** [comment]
:+1:

**Comment by scottefein** [comment]
You want to make the pull request and I'll pull it in?

**Comment by nathany** [comment]
I'd prefer if you just update it. Thanks.
