### ISSUE TITLE
The use of "tolerance"

### ISSUE THREAD

**Issue by lambdahands** [scottefein/the-happiness-manifesto#9]
First off, nice work on presenting something to the developer community that's focused on the health of the people involved.

_"I value respect and tolerance to all in my community"_

is a good start, but "tolerance" doesn't exactly cut it when discussing respect and equality. The term leaves out important things like _understanding and empathy_, which I think the community certainly needs more of.

So many something along the lines of:

_I value respect and **compassion** to all in my community_

Maybe compassion is too strong of a word. Maybe "understanding" is better. Thoughts?

**Comment by scottefein** [comment]
The original tilt towards tolerance was based on a want of using a term that was apart of the vernacular when referring to issues of gender, race, orientation etc. That being said, using the term understanding doesn't seem to take away much from the meaning. 

I value respect, understanding, and tolerance to all in my community?

**Comment by lambdahands** [comment]
I'd say that's fair. :smile: Tolerance by itself simply means to endure something uncomfortable. It's a step in achieving social equality, but my main qualm with the term is that people can be tolerant yet unhelpful and divisive.

Adding understanding to the mix, however, clarifies the direction in which the community is invested in. Thanks for hearing me out!

**Comment by RichardLitt** [comment]
I'd say that's fair, too. :+1:

**Comment by scottefein** [comment]
Updated here: https://github.com/scottefein/the-happiness-manifesto/commit/425ce970cede909708473802915c6e1bb1cde447
